### ISSUE TITLE
Original source maps may not be uploaded at all

### ISSUE THREAD

**Issue by phcoliveira** [jscrambler/ember-cli-jscrambler#1]
Hello again.

After the release of the version `5.2.3`, `ember-cli-deploy-bugsnag` uploads all source maps correctly, leading me to believe it didn't work before due [this bug in version `5.2.2`](https://github.com/jscrambler/jscrambler/issues/4).

But the final source maps, for the protected and minified files, recreate the original compilations from Babel, transpilled from ES6 to ES5. I had the impression that the original source maps, for the development files written in ES6, should be merged to the final one, according to [Jscrambler's docs](https://docs.jscrambler.com/code-integrity/documentation/source-maps/api).

I think the original source maps, for the development files in ES6, are note being uploaded at all. What makes me think that is Jscrambler's assumption for the file paths of a given source map and its correlated Javascript file. According to the docs, if a Javascript file has a path given by `assets/application.js`, its correlated source map should have a path of `assets/application.js.map` in order to be automatically uploaded to be merged into the final source map, for the protected file.

The problem with this approach is that Ember-CLI offers no way for customizing the file path of a source map. Even after disabling the `fingerprint` option in `ember-cli-build`, which naturally breaks Jscrambler's assumption, we would have the pair `assets/application.js` and `assets/application.map`.

Am I right to assume the final source map trace the errors back to the concatenated, transpilled application file because the original source maps are not being uploaded at all?

**Comment by CMatias** [comment]
Hi @phcoliveira, since this project has been moved and the issue fixed (if I'm not mistaken) I'm going to close this.
